spring:
  dubbo:
    application:
      name: word-enquiry-provider

    registry:
      address: zookeeper://localhost:2181

    protocol:
      name: dubbo
      port: 20880

    scan: demo.kilodleif.provider.service